### PR TITLE
Add Code of Conduct and Security policies

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan @cevich PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@cevich Please merge.

**Comment by cevich** [comment]
@TomSweeneyRedHat Thanks so much for adding this!

**Comment by cevich** [comment]
@TomSweeneyRedHat can you sign your commits please :grin:

**Comment by cevich** [comment]
(In case I don't get to it before my PTO, LGTM provided a signed commit and passing tests, go ahead and manually merge)

**Comment by cevich** [comment]
(If I don't get to this before my PTO, it LGTM for manual merge assuming a signed commit and passing tests.  I added Tom as a maintainer for this repo.)

**Comment by TomSweeneyRedHat** [comment]
Repushed, I woulda swore I signed it initially.

**Comment by cevich** [comment]
@TomSweeneyRedHat It's complaining about your commit not having a gpg-signature.  I can turn that option off...

**Comment by cevich** [comment]
...option disabled.  It's likely I'm being too paranoid.

**Pull request merged**
