### PR TITLE
fix broken renovate config

### PR DESCRIPTION
**Pull request by Luap99**
checked with:
podman run -it \
-v ./renovate/defaults.json5:/usr/src/app/renovate.json5:z \ docker.io/renovate/renovate:latest \
renovate-config-validator

Due the nested packageRules section in golang the auto migration is not working correctly and caused an error for us. This caused renovate to propse PRs without the proper settings.
Fix the config by (hopefully) migrating correctly to the new format. The nested packageRule is now on the same level which should fix the breakage. The config validator is happy now but I have no way of actually testing if this still works correctly, I guess we will find out.

output of the validate tool on the old (now) broken conf:
```
$  podman run -it \
        -v ./renovate/defaults.json5:/usr/src/app/renovate.json5:z \
        docker.io/renovate/renovate:latest \
        renovate-config-validator
 INFO: Validating renovate.json5
 WARN: Config migration necessary
       "oldConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "description": "This is a basic preset intended  for reuse to reduce the amount of boiler-plate  configuration that otherwise would need to be  duplicated. It should be referenced from other  repositories renovate config under the 'extends'  section as:  github>containers/automation//renovate/defaults.json5  (optionally with a '#X.Y.Z' version-tag suffix).",
         "extends": ["config:base", ":gitSignOff", ":rebaseStalePrs"],
         "timezone": "UTC",
         "prHourlyLimit": 1,
         "labels": ["dependencies"],
         "vulnerabilityAlerts": {
           "labels": ["dependencies", "security"],
           "enabled": true,
           "packageRules": [
             {
               "matchManagers": ["gomod"],
               "matchDepTypes": ["indirect"],
               "enabled": true
             }
           ]
         },
         "rebaseWhen": "never",
         "golang": {
           "postUpdateOptions": ["gomodTidy"],
           "rollbackPrs": false,
           "rangeStrategy": "replace",
           "packageRules": [
             {
               "matchUpdateTypes": ["digest"],
               "schedule": ["after 1am and before 11am on the first day of the month"]
             },
             {
               "matchPackageNames": ["github.com/containers/common"],
               "allowedVersions": "!/v((1.0.0)|(1.0.1))$/"
             }
           ]
         },
         "rust": {"rangeStrategy": "bump"},
         "python": {"rangeStrategy": "replace"},
         "regexManagers": [
           {
             "fileMatch": "^.cirrus.yml$",
             "matchStrings": ["c(?<currentValue>20\\d{6}t\\d{6}z-\\w+)"],
             "depNameTemplate": "containers/automation_images",
             "datasourceTemplate": "github-tags",
             "versioningTemplate": "loose",
             "autoReplaceStringTemplate": "c{{{newVersion}}}"
           },
           {
             "fileMatch": "^Makefile$",
             "matchStrings": [
               "GOLANGCI_LINT_VERSION\\s+:=\\s+(?<currentValue>.+)\\s*"
             ],
             "depNameTemplate": "golangci/golangci-lint",
             "datasourceTemplate": "github-releases",
             "versioningTemplate": "semver-coerced",
             "extractVersionTemplate": "v(?<version>.+)"
           }
         ],
         "packageRules": [
           {"matchLanguages": ["go"], "rollbackPrs": true},
           {
             "matchManagers": ["github-actions"],
             "matchDepTypes": ["action"],
             "commitMessagePrefix": "[skip-ci]"
           },
           {
             "matchManagers": ["regex"],
             "matchFiles": [".cirrus.yml"],
             "groupName": "CI VM Image",
             "reviewers": ["cevich"],
             "schedule": ["at any time"]
           }
         ]
       },
       "newConfig": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "description": "This is a basic preset intended  for reuse to reduce the amount of boiler-plate  configuration that otherwise would need to be  duplicated. It should be referenced from other  repositories renovate config under the 'extends'  section as:  github>containers/automation//renovate/defaults.json5  (optionally with a '#X.Y.Z' version-tag suffix).",
         "extends": ["config:recommended", ":gitSignOff", ":rebaseStalePrs"],
         "timezone": "UTC",
         "prHourlyLimit": 1,
         "labels": ["dependencies"],
         "vulnerabilityAlerts": {
           "labels": ["dependencies", "security"],
           "enabled": true,
           "packageRules": [
             {
               "matchManagers": ["gomod"],
               "matchDepTypes": ["indirect"],
               "enabled": true
             }
           ]
         },
         "rebaseWhen": "never",
         "regexManagers": [
           {
             "fileMatch": "^.cirrus.yml$",
             "matchStrings": ["c(?<currentValue>20\\d{6}t\\d{6}z-\\w+)"],
             "depNameTemplate": "containers/automation_images",
             "datasourceTemplate": "github-tags",
             "versioningTemplate": "loose",
             "autoReplaceStringTemplate": "c{{{newVersion}}}"
           },
           {
             "fileMatch": "^Makefile$",
             "matchStrings": [
               "GOLANGCI_LINT_VERSION\\s+:=\\s+(?<currentValue>.+)\\s*"
             ],
             "depNameTemplate": "golangci/golangci-lint",
             "datasourceTemplate": "github-releases",
             "versioningTemplate": "semver-coerced",
             "extractVersionTemplate": "v(?<version>.+)"
           }
         ],
         "packageRules": [
           {"matchCategories": ["rust"], "rangeStrategy": "bump"},
           {"matchCategories": ["python"], "rangeStrategy": "replace"},
           {
             "matchCategories": ["golang"],
             "postUpdateOptions": ["gomodTidy"],
             "rollbackPrs": false,
             "rangeStrategy": "replace",
             "matchUpdateTypes": ["digest"],
             "schedule": ["after 1am and before 11am on the first day of the month"]
           },
           {
             "matchCategories": ["golang"],
             "postUpdateOptions": ["gomodTidy"],
             "rollbackPrs": false,
             "rangeStrategy": "replace",
             "matchPackageNames": ["github.com/containers/common"],
             "allowedVersions": "!/v((1.0.0)|(1.0.1))$/"
           },
           {"matchCategories": ["go"], "rollbackPrs": true},
           {
             "matchManagers": ["github-actions"],
             "matchDepTypes": ["action"],
             "commitMessagePrefix": "[skip-ci]"
           },
           {
             "matchManagers": ["regex"],
             "matchFileNames": [".cirrus.yml"],
             "groupName": "CI VM Image",
             "reviewers": ["cevich"],
             "schedule": ["at any time"]
           }
         ]
       }
ERROR: Found errors in configuration
       "file": "renovate.json5",
       "errors": [
         {
           "topic": "Configuration Error",
           "message": "packageRules[2]: packageRules cannot combine both matchUpdateTypes and rangeStrategy. Rule: {\"matchCategories\":[\"golang\"],\"postUpdateOptions\":[\"gomodTidy\"],\"rollbackPrs\":false,\"rangeStrategy\":\"replace\",\"matchUpdateTypes\":[\"digest\"],\"schedule\":[\"after 1am and before 11am on the first day of the month\"]}"
         },
         {
           "topic": "Configuration Error",
           "message": "packageRules[2]: packageRules cannot combine both matchUpdateTypes and rollbackPrs. Rule: {\"matchCategories\":[\"golang\"],\"postUpdateOptions\":[\"gomodTidy\"],\"rollbackPrs\":false,\"rangeStrategy\":\"replace\",\"matchUpdateTypes\":[\"digest\"],\"schedule\":[\"after 1am and before 11am on the first day of the month\"]}"
         }
       ]
```

### CODE REVIEW

**Comment by Luap99** [comment]
@vrothberg @edsantiago PTAL. I suggest we just yolo this and see if renovate PRs will work again. Chris is unfortunately  out, as usual perfect timing on these things.

**Review by vrothberg — COMMENTED** [review]
LGTM
#yolo

**Comment by edsantiago** [comment]
I've never even looked at anything related to renovatebot but shrug, okay, yolo. 

/lgtm
/hold

Could you pretty-please update the top comment, though, and include a better description than "not working correctly" and "caused an error for us"? Maybe a link to an actual error, and an excerpt including the error(s)?

**Comment by Luap99** [comment]
I added the output of the validate tool, the PRs currently are missing the important go mod tidy step which trips the git diff check after the `make vendor` in podman.
@vrothberg already force pushed the PRs with the problem: https://github.com/containers/podman/pull/19199 so I cannot show you the real failure.

**Comment by vrothberg** [comment]
The problem was that the `go.sum` file hasn't been updated properly.

**Comment by edsantiago** [comment]
Thank you. Please feel free to merge; I do not have privs on this repo.

**Comment by cevich** [comment]
Finally getting a chance to look at this.  Paul the config. changes look fine and good to me, it also simplifies things quite a bit :+1: 

As for the YOLO, unfortunately this is somewhat necessary given this is the inherited default config. for all repos.  There's only so much validation you can do.  It's very common to realize something broke and do a follow-up PR as you did.  I don't have a good solution for this, or at least one doesn't a YOLO merge somewhere.

**Pull request merged**
